spring.datasource.url: jdbc:mysql://localhost:3306/todolist
spring.datasource.username: root
spring.datasource.password: dGCvkabb97
spring.jpa.hibernate.ddl-auto: update
someParameter: 1337
spring:
  jpa:
    database-platform=org:
      hibernate:
        dialect:
          MySQL5Dialect: